#!/bin/bash

url=$1

yt-dlp \
--no-playlist \
--output '~/downloads/audio/%(title)s.%(ext)s' \
--restrict-filenames \
--trim-filenames 250 \
--no-cache-dir \
--dump-json \
--no-simulate \
--audio-quality 0 \
--audio-format mp3 \
--extract-audio \
$url
